// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Azure AD Reporting Api")]
[assembly: AssemblyProductAttribute("Azure AD Reporting Api")]
[assembly: AssemblyDescriptionAttribute("Azure AD Reporting Api")]
[assembly: AssemblyVersionAttribute("1.0.1.2")]
[assembly: AssemblyFileVersionAttribute("1.0.1.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.1.2";
    }
}
